---
       - name: Checking a simple command
         command: "whoami"

       - name: install Apache 
         apt: 
           name: apache2, php7.4 , php-mysql, libapache2-mod-php 
           state: present 
         become: yes

       - name: Change ownership of foler
         ansible.builtin.file:
                 path: /var/www/html
                 state: directory
                 recurse: yes
                 owner: ubuntu
                 group: ubuntu

       - name: Move index.html
         ansible.builtin.copy: 
           src: index.html
           dest: /var/www/html/

       - name: Restart Apache Service
         ansible.builtin.service:
                name: apache2
                state: restarted
         become: yes 

